export const mockEvents = [
  {
    _id: '65f001aab411240f159b82b1',
    taskId: { taskName: '化学实验课安全巡检任务' },
    state: 'pending',
    reportDate: '2026-03-01T08:20:00.000Z',
    labels: [{ name: '未佩戴护目镜', color: 'red' }, { name: '区域逗留', color: 'gold' }],
    desc: '实验区北侧工位检测到未规范佩戴护目镜，持续约 43 秒。',
    locationName: '实验楼A区-北侧工位',
    cameraName: 'A区摄像头-01',
    picsNames: ['/event-snapshot.svg'],
  },
  {
    _id: '65f001aab411240f159b82b2',
    taskId: { taskName: '电工实验课动作监测任务' },
    state: 'uploaded',
    reportDate: '2026-03-01T09:10:00.000Z',
    labels: [{ name: '危险动作', color: 'volcano' }],
    desc: '检测到疑似高风险动作，系统已自动上报值班人员。',
    locationName: '实验楼B区-机械实训间',
    cameraName: 'B区摄像头-03',
    picsNames: ['/event-snapshot.svg'],
  },
  {
    _id: '65f001aab411240f159b82b3',
    taskId: { taskName: '晚间实验室秩序巡检任务' },
    state: 'finish',
    reportDate: '2026-03-01T10:35:00.000Z',
    labels: [{ name: '人员聚集', color: 'blue' }],
    desc: '短时人员聚集事件已完成现场处置与记录归档。',
    locationName: '实验楼C区-门厅',
    cameraName: 'C区摄像头-02',
    picsNames: ['/event-snapshot.svg'],
  },
  {
    _id: '65f001aab411240f159b82b4',
    taskId: { taskName: '嵌入式实验设备状态监测任务' },
    state: 'pending',
    reportDate: '2026-03-01T13:15:00.000Z',
    labels: [{ name: '设备异常停机', color: 'magenta' }],
    desc: '设备工位连续 12 分钟无状态上报，建议巡检确认。',
    locationName: '实验楼A区-设备工位4',
    cameraName: 'A区摄像头-05',
    picsNames: ['/event-snapshot.svg'],
  },
  {
    _id: '65f001aab411240f159b82b5',
    taskId: { taskName: '数电实验安全巡检任务' },
    state: 'uploaded',
    reportDate: '2026-03-01T15:05:00.000Z',
    labels: [{ name: '未按流程操作', color: 'purple' }],
    desc: '识别到流程偏离行为，系统已自动记录并上报。',
    locationName: '实验楼B区-化学实验台2',
    cameraName: 'B区摄像头-01',
    picsNames: ['/event-snapshot.svg'],
  },
  {
    _id: '65f001aab411240f159b82b6',
    taskId: { taskName: '计算机组成实验巡检任务' },
    state: 'finish',
    reportDate: '2026-03-01T16:28:00.000Z',
    labels: [{ name: '实验台占用超时', color: 'geekblue' }],
    desc: '晚课前存在实验台超时占用，已由管理员现场清理。',
    locationName: '实验楼C区-机房3',
    cameraName: 'C区摄像头-07',
    picsNames: ['/event-snapshot.svg'],
  },
  {
    _id: '65f001aab411240f159b82b7',
    taskId: { taskName: '排课冲突辅助监测任务' },
    state: 'pending',
    reportDate: '2026-03-02T08:42:00.000Z',
    labels: [{ name: '排课冲突预警', color: 'orange' }],
    desc: '同一实验室在 10:00-12:00 检测到两门课程预占冲突。',
    locationName: '实验楼A区-A101',
    cameraName: 'A区摄像头-11',
    picsNames: ['/event-snapshot.svg'],
  },
  {
    _id: '65f001aab411240f159b82b8',
    taskId: { taskName: '实验排课执行监控任务' },
    state: 'uploaded',
    reportDate: '2026-03-02T09:55:00.000Z',
    labels: [{ name: '教师未到场', color: 'red' }],
    desc: '课程开始后 10 分钟教师未到场，系统已自动上报。',
    locationName: '实验楼B区-B203',
    cameraName: 'B区摄像头-09',
    picsNames: ['/event-snapshot.svg'],
  },
  {
    _id: '65f001aab411240f159b82b9',
    taskId: { taskName: '实验室资源利用率监测任务' },
    state: 'finish',
    reportDate: '2026-03-02T11:30:00.000Z',
    labels: [{ name: '空置率偏高', color: 'cyan' }],
    desc: '课程结束后资源空置超过阈值，已形成优化建议。',
    locationName: '实验楼C区-C305',
    cameraName: 'C区摄像头-04',
    picsNames: ['/event-snapshot.svg'],
  },
  {
    _id: '65f001aab411240f159b82ba',
    taskId: { taskName: '实验课秩序维护任务' },
    state: 'pending',
    reportDate: '2026-03-02T13:48:00.000Z',
    labels: [{ name: '迟到聚集', color: 'gold' }],
    desc: '上课前出现迟到学生聚集，建议辅导员引导分流。',
    locationName: '实验楼A区-走廊',
    cameraName: 'A区摄像头-12',
    picsNames: ['/event-snapshot.svg'],
  },
  {
    _id: '65f001aab411240f159b82bb',
    taskId: { taskName: '实验台安全行为识别任务' },
    state: 'uploaded',
    reportDate: '2026-03-02T15:05:00.000Z',
    labels: [{ name: '佩戴不规范', color: 'volcano' }],
    desc: '识别到防护手套佩戴不规范，已自动推送值班端。',
    locationName: '实验楼B区-实验台6',
    cameraName: 'B区摄像头-08',
    picsNames: ['/event-snapshot.svg'],
  },
  {
    _id: '65f001aab411240f159b82bc',
    taskId: { taskName: '夜间实验排班巡检任务' },
    state: 'finish',
    reportDate: '2026-03-02T18:20:00.000Z',
    labels: [{ name: '夜间未授权进入', color: 'red' }],
    desc: '夜间门禁异常进入已核验并完成处置。',
    locationName: '实验楼C区-门禁',
    cameraName: 'C区摄像头-10',
    picsNames: ['/event-snapshot.svg'],
  },
];

export const mockFaceEvents = [
  {
    id: 'face-001',
    name: '访客A',
    confidence: 93,
    time: '2026-03-01 08:31:24',
    location: '实验楼A区门禁',
    image: '/face-snapshot.svg',
  },
  {
    id: 'face-002',
    name: '访客B',
    confidence: 88,
    time: '2026-03-01 10:05:12',
    location: '实验楼B区走廊',
    image: '/face-snapshot.svg',
  },
  {
    id: 'face-003',
    name: '教师C',
    confidence: 96,
    time: '2026-03-01 14:42:39',
    location: '实验楼C区门厅',
    image: '/face-snapshot.svg',
  },
];

export function toStateText(state: string) {
  if (state === 'pending') return '等待处理';
  if (state === 'uploaded') return '已上报';
  if (state === 'finish') return '已解决';
  return state;
}

export function toBadgeStatus(state: string): 'processing' | 'success' | 'default' {
  if (state === 'pending') return 'processing';
  if (state === 'uploaded') return 'success';
  return 'default';
}
